apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: checkout
spec:
  params:
    - name: repo-url
      description: The URL of the repository to clone
      type: string
    - name: branch
      description: The branch to checkout
      type: string
  steps:
    - name: checkout-repo
      image: bitnami/git:latest
      command: [git]
      args: ["clone", "$(params.repo-url)", "--branch" , "$(params.branch)"]
