apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-pipeline
spec:
  params:
    - name: message
      type: string
      description: The message to echo
  tasks:
    - name: echo
      taskRef:
        name: echo
      params:
        - name: message
          value: $(params.message)

---

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: source
  params:
    - name: repo-url
      type: string
      description: The URL of the repository to clone
    - name: branch
      type: string
      description: The branch to checkout
  tasks:
    - name: clone-and-checkout
      taskRef:
        name: clone-and-checkout
      workspaces:
        - name: source
          workspace: source
      params:
        - name: repo-url
          value: $(params.repo-url)
        - name: branch
          value: $(params.branch)
    - name: lint
      taskRef:
        name: echo
      runAfter:
        - clone-and-checkout
      params:
        - name: message
          value: "Calling Flake8 linter..."
    - name: tests
      taskRef:
        name: echo
      runAfter:
        - lint
      params:
        - name: message
          value: "Running unit tests with PyUnit..."
    - name: build
      taskRef:
        name: echo
      runAfter:
        - tests
      params:
        - name: message
          value: "Building image for $(params.repo-url)"
    - name: deploy
      taskRef:
        name: echo
      runAfter:
        - build
      params:
        - name: message
          value: "Deploying $(params.branch) branch of $(params.repo-url)"
